# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-28 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpay_Payment_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proforma_ids', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_ids', models.CharField(blank=True, max_length=50, null=True)),
                ('redirect_ok_url', models.CharField(blank=True, max_length=208, null=True)),
                ('redirect_fail_url', models.CharField(blank=True, max_length=208, null=True)),
                ('status', models.CharField(choices=[(b'generated', b'generated'), (b'success', b'success'), (b'fail', b'fail')], max_length=9)),
            ],
        ),
    ]
