# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-28 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silver_cpay', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cpay_Payment_Request',
            new_name='Payment_Request',
        ),
    ]
