# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-29 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silver_cpay', '0002_auto_20190128_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'success', b'success'), (b'fail', b'fail')], default=b'generated', max_length=9)),
            ],
        ),
        migrations.AlterField(
            model_name='payment_request',
            name='status',
            field=models.CharField(choices=[(b'generated', b'generated'), (b'success', b'success'), (b'fail', b'fail')], default=b'generated', max_length=9),
        ),
        migrations.AddField(
            model_name='notification',
            name='payment_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silver_cpay.Payment_Request'),
        ),
    ]
