# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-30 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silver_cpay', '0005_auto_20190129_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.CharField(default='{}', max_length=5000),
            preserve_default=False,
        ),
    ]
