# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-30 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silver_cpay', '0006_notification_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_request',
            name='data',
            field=models.CharField(default='{}', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_request',
            name='post_url',
            field=models.CharField(default='', max_length=208),
            preserve_default=False,
        ),
    ]
