# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 13:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPageAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features_header', models.CharField(max_length=500)),
                ('features_text', models.CharField(max_length=500)),
                ('features_image', models.URLField(max_length=500)),
                ('company_page', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='va_saas.CompanyPage')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPageAboutSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_header', models.CharField(max_length=500)),
                ('step_details', models.CharField(max_length=500)),
                ('belongs_to_page', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='va_saas.CompanyPageAbout')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPageFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_image', models.ImageField(max_length=500, upload_to='')),
                ('feature_header', models.CharField(max_length=500)),
                ('feature_details', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPageFeaturesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_page', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='va_saas.CompanyPage')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPageLanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_logo', models.URLField(max_length=300)),
                ('landing_header', models.CharField(max_length=600)),
                ('landing_text', models.CharField(max_length=600)),
                ('landing_image', models.URLField(max_length=600)),
                ('footer_logo', models.URLField(max_length=600)),
                ('footer_text', models.CharField(max_length=600)),
                ('footer_facebook', models.URLField(max_length=600)),
                ('footer_twitter', models.URLField(max_length=600)),
                ('footer_youtube', models.URLField(max_length=600)),
                ('footer_instagram', models.URLField(max_length=600)),
                ('company_page', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='va_saas.CompanyPage')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPageLoggedIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_text', models.CharField(max_length=500)),
                ('support_email', models.CharField(max_length=500)),
                ('company_page', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='va_saas.CompanyPage')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPagePricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_header', models.CharField(max_length=500)),
                ('pricing_details', models.CharField(max_length=500)),
                ('company_page', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='va_saas.CompanyPage')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPageSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_text', models.CharField(max_length=500)),
                ('company_page', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='va_saas.CompanyPage')),
            ],
        ),
        migrations.CreateModel(
            name='VAHook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(db_index=True, max_length=64, verbose_name='Event')),
                ('target', models.URLField(max_length=255, verbose_name='Target URL')),
                ('headers', models.CharField(default='{}', max_length=200)),
                ('method', models.CharField(default='get', max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vahooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='companypagefeature',
            name='belongs_to_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='va_saas.CompanyPageFeaturesList'),
        ),
    ]
