# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 09:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
#        ('silver', '0050_auto_20190410_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlanFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_image', models.ImageField(upload_to='')),
                ('plan_description', models.CharField(max_length=200)),
                ('plan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='silver.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='StepField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(max_length=20)),
                ('value', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silver_extensions.PlanFeatures')),
            ],
        ),
        migrations.CreateModel(
            name='UserCustomerMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silver.Customer')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silver_extensions.MappingType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
