# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silver_extensions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlanSteps',
            new_name='StepFields',
        ),
    ]
