# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silver_extensions', '0002_auto_20190527_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='stepfields',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silver_extensions.PlanSteps'),
        ),
    ]
