# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silver_extensions', '0004_auto_20190527_1320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlanSteps',
            new_name='PlanStep',
        ),
        migrations.RenameModel(
            old_name='StepFields',
            new_name='StepField',
        ),
        migrations.RenameField(
            model_name='stepfield',
            old_name='step_input_type',
            new_name='input_type',
        ),
        migrations.RenameField(
            model_name='stepfield',
            old_name='step_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='stepfield',
            old_name='step_value',
            new_name='value',
        ),
    ]
