# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silver_extensions', '0004_auto_20190527_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planstep',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silver_extensions.PlanFeatures'),
        ),
    ]
