# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silver_extensions', '0006_auto_20190527_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepfield',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stepfield',
            name='verification',
            field=models.CharField(blank=True, choices=[('email', 'email'), ('file', 'file')], default='', max_length=10, null=True),
        ),
    ]
